Integrate C-IL for multi-label classification
openvinotoolkit/model_preparation_algorithm pull request #15
Opened 2022-06-08 02:19 UTC by JihwanEom

## Summary
### This PR includes :
- Integrate class-incremental learning for multi-label classification
- Improve stability in stage.py

2022-06-10 04:52 UTC, harimkang requested changes

2022-06-10 04:52 UTC, harimkang commented on mpa/cls/stage.py
> +        if 'Multi' in cfg.model.head.get('type', False) and cfg.model.head.get('topk', False):
Can't we use cfg.task as the standard (not head.type)?
I think we can also combine this if statement with 79-80 line and use it as one if statement.

2022-06-10 04:52 UTC, harimkang commented on models/classification/ote_efficientnet_b0_multilabel.yaml
> +            type: AsymmetricLoss
need to add new line

2022-06-10 04:52 UTC, harimkang commented on mpa/cls/stage.py
> +                if 'Multi' not in cfg.model.head.type:
As in the previous comment, we can use (head.type ->) cfg.task as the standard task type.

2022-06-10 05:02 UTC, harimkang commented on mpa/cls/stage.py
> +        if 'Multi' in cfg.model.head.get('type', False) and cfg.model.head.get('topk', False):
sorry, I was mistaken. This is using the same cfg.task as 'classification'.
I think you can change cfg.task to multi-label classification from classification 
or The conditional statement {'Multi' in cfg.model.head.get('type') }needs to be reconsidered. (need to be more specific.)

2022-06-10 05:02 UTC, harimkang commented on mpa/cls/stage.py
> +                if 'Multi' not in cfg.model.head.type:
Same as above comment.

2022-06-14 09:51 UTC, goodsong81 approved these changes
LGTM. Please resolve Harim's comments.

2022-06-23 13:44 UTC, harimkang requested changes
I left a few comments.

2022-06-23 13:44 UTC, harimkang commented on mpa/cls/stage.py
> +                if not cfg.model.get('multilabel', False):
'If not' doesn't look good, do you have any other ideas?

2022-06-23 13:44 UTC, harimkang commented on mpa/cls/stage.py
> +            if cfg.model.get('multilabel', False):
how about
```
cfg.model.head.topk = (1,) if cfg.model.head.num_classes < 5 else (1, 5)
if cfg.model.get('multilabel', False): cfg.model.head.pop('topk', None)
```

2022-06-23 17:03 UTC, JihwanEom commented on mpa/cls/stage.py
> +            if cfg.model.get('multilabel', False):
How do you think about below code?

```
cfg.model.head.topk = (1, cfg.model.head.num_classes) if cfg.model.head.num_classes < 5 else (1, 5)
if cfg.model.get('multilabel', False): cfg.model.head.pop('topk', None)
```

2022-06-23 17:03 UTC, JihwanEom commented on mpa/modules/models/classifiers/sam_classifier.py
> +        if 'multilabel' in kwargs:
@harimkang this multilabel flag is needed only for state_dict_hook. How do you think about separating state_dict_hook into two cases: 1) backbone, 2) head
If we separate this, each classifier will not have to remove multilabel argument. But I think state_dict hook in heads might be implemented.

2022-06-29 07:34 UTC, harimkang approved these changes
LGTM.
Need to check that there are no conflicts with recently merged code.

2022-06-29 08:24 UTC, supersoob approved these changes
LGTM

2022-06-29 23:52 UTC, merged