Disable EMA hook for classification task
openvinotoolkit/model_preparation_algorithm pull request #44
Opened 2022-08-16 05:21 UTC by supersoob

This PR includes

- Disable EMA hook for classification task
- Lower priority of EvalHook

2022-08-18 08:41 UTC, jaegukhyun requested changes
There are some of flake8 issues

2022-08-18 08:44 UTC, goodsong81 approved these changes
LGTM. But not sure to remove it also from Semi-SL recipe.
@harimkang Could you confirm?

2022-08-18 16:01 UTC, JihwanEom approved these changes
LGTM

2022-08-19 01:04 UTC, jaegukhyun approved these changes
LGTM

2022-08-19 01:07 UTC, harimkang requested changes

2022-08-19 01:07 UTC, harimkang commented on recipes/stages/classification/semisl.yaml
> -- type: SemiSLClsHook
I think SemiSL should first leave the EMA as it is.

2022-08-19 05:36 UTC, harimkang approved these changes

2022-08-19 05:44 UTC, goodsong81 approved these changes

2022-08-19 05:44 UTC, merged