Kp/add seeds freezing
openvinotoolkit/model_preparation_algorithm pull request #63
Opened 2022-09-22 14:56 UTC by kprokofi

2022-09-22 15:00 UTC, sovrasov commented on mpa/utils/config_utils.py
> +
Please add one mere blank line here to preserve the code style.

2022-09-22 15:06 UTC, kprokofi commented on mpa/utils/config_utils.py
> +
Sure, thanks

2022-09-22 15:15 UTC, sovrasov approved these changes

2022-09-23 01:23 UTC, JihwanEom requested changes
Hi, could you make some changes on this PR?

1. please retarget to develop branch, release branch is fixed now.
2. please remove seed/deterministic changes, it is duplicated with stage.py. https://github.com/openvinotoolkit/model_preparation_algorithm/blob/develop/mpa/stage.py#L130

Thank you!

2022-09-26 06:54 UTC, closed without merging