Dk/otx xai det
openvinotoolkit/model_preparation_algorithm pull request #85
Opened 2022-11-15 03:00 UTC by dongkwan-kim01

**Summary**
Support explain mode to MPA detection

**This PR includes**
Add `DetectionExplainer` class to mpa/det/explainer.py
Add explain stage

**Test Codes**
Can test with OTX CLI(please refer OTX cli support, [link](https://github.com/openvinotoolkit/training_extensions/pull/1342))

2022-12-16 05:44 UTC, dongkwan-kim01 commented
@goodsong81 @negvet @harimkang Hello, because of the termination date, could you review this PR?

2022-12-16 13:38 UTC, negvet approved these changes
Thanks for the work. LGTM

2022-12-16 13:38 UTC, negvet commented on mpa/det/inferrer.py
> +        if isinstance(dataset, ImageTilingDataset):
Supporting `ImageTilingDataset` on the way.. It is better to do it separately, but not sure that we can afford it in terms of time. I would approve to keep it here :)

2022-12-19 02:15 UTC, goodsong81 requested changes
Need minor fixes.

2022-12-19 02:15 UTC, goodsong81 commented on mpa/cls/inferrer.py
> +               'Number of elements should be the same, however, number of outputs are ' \
Double quotes, please :)

2022-12-19 02:15 UTC, goodsong81 commented on mpa/det/inferrer.py
> +               'Number of elements should be the same, however, number of outputs are ' \
Same here.

2022-12-20 07:44 UTC, goodsong81 requested changes
Could you resolve the conflict?
Sorry for late review, it's my bad.

2022-12-20 08:03 UTC, dongkwan-kim01 commented
@goodsong81 Thank you for noticing. Resolved conflict and tested in the otx side.

2022-12-20 09:23 UTC, goodsong81 approved these changes

2022-12-20 09:24 UTC, merged